//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employers()
        {
            this.New_Employees = new HashSet<New_Employees>();
        }
    
        public int Employer_ID { get; set; }
        public string Employer_Name { get; set; }
        public int Position_ID { get; set; }
        public string Employee_Last_Name { get; set; }
        public string Employee_Middle_Name { get; set; }
        public int Authorization_ID { get; set; }
        public int ID_Roles { get; set; }
    
        public virtual User_Authentication User_Authentication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<New_Employees> New_Employees { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual Position Position { get; set; }
    }
}
