//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class prEntities : DbContext
    {
        public prEntities()
            : base("name=prEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Employers> Employers { get; set; }
        public virtual DbSet<Nationality> Nationality { get; set; }
        public virtual DbSet<New_Employees> New_Employees { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<Store> Store { get; set; }
        public virtual DbSet<Training_Data> Training_Data { get; set; }
        public virtual DbSet<User_Authentication> User_Authentication { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
    }
}
