//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr5
{
    using System;
    using System.Collections.Generic;
    
    public partial class New_Employees
    {
        public int New_Employee_ID { get; set; }
        public string Employee_Last_Name { get; set; }
        public System.DateTime Date_of_Birth { get; set; }
        public int Employer_ID { get; set; }
        public int Position_ID { get; set; }
        public int Nationality_ID { get; set; }
        public int Training_Data_ID { get; set; }
        public string Employee_First_Name { get; set; }
        public string Employee_Middle_Name { get; set; }
        public int ID_Roles { get; set; }
    
        public virtual Employers Employers { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual Position Position { get; set; }
        public virtual Training_Data Training_Data { get; set; }
    }
}
