//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Order_ID { get; set; }
        public int Client_ID { get; set; }
        public int Employee_ID { get; set; }
        public string Order_Number { get; set; }
        public System.DateTime Order_Date { get; set; }
        public int Store_ID { get; set; }
        public int Status_ID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Store Store { get; set; }
    }
}
